trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  storageAccountName: "<your-storage-account-name>"
  containerName: "<your-container-name>"
  blobName: "VSCodeSetup-x64-1.96.4.exe"
  sasToken: "<your-sas-token>"
  targetPath: "C:\\Temp\\VSCodeSetup-x64-1.96.4.exe"

stages:
- stage: DeployVSCode
  jobs:
  - job: DeployToVM
    displayName: "Install VSCode on Azure VMs"
    steps:
    - task: PowerShell@2
      displayName: "Download and Install VSCode"
      inputs:
        targetType: inline
        script: |
          # Define variables
          $storageAccountName = "$(storageAccountName)"
          $containerName = "$(containerName)"
          $blobName = "$(blobName)"
          $sasToken = "$(sasToken)"
          $targetPath = "$(targetPath)"
          
          # Form the URL to the blob
          $blobUrl = "https://$storageAccountName.blob.core.windows.net/$containerName/$blobName?$sasToken"
          
          # Create directory if not exists
          $targetDir = Split-Path -Path $targetPath
          if (!(Test-Path -Path $targetDir)) {
              New-Item -ItemType Directory -Path $targetDir
          }

          # Download the file
          Write-Host "Downloading $blobUrl to $targetPath"
          Invoke-WebRequest -Uri $blobUrl -OutFile $targetPath

          # Install the .exe silently
          Write-Host "Installing $targetPath"
          Start-Process -FilePath $targetPath -ArgumentList "/silent /verysilent /norestart" -Wait

          Write-Host "Installation completed."