trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: '<Your-Service-Connection-Name>'
  resourceGroupName: '<Your-Resource-Group>'
  vmName: '<Your-VM-Name>'

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(azureSubscription)
    ScriptType: 'InlineScript'
    Inline: |
      try {
          $resourceGroup = "$(resourceGroupName)"
          $vmName = "$(vmName)"

          # Execute RunCommand on the Azure VM
          $commandId = 'RunPowerShellScript'
          $script = @'
          Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* |
          Select-Object DisplayName, DisplayVersion, Publisher, InstallDate
          '@

          # Run the command on the VM
          $result = Invoke-AzVMRunCommand -ResourceGroupName $resourceGroup -Name $vmName -CommandId $commandId -ScriptString $script

          # Output the result
          $result.Value | ForEach-Object { $_.Message }
      }
      catch {
          Write-Error "An error occurred while running the command on the VM: $_"
          throw
      }
    azurePowerShellVersion: 'LatestVersion'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Installed software information retrieved successfully."